# Netlify Configuration for Les Dauphins Portal

[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite outputs to 'dist' by default)
  publish = "dist"
  
  # Node version
  environment = { NODE_VERSION = "18", SECRETS_SCAN_ENABLED = "false" }

# Redirect rules for Single Page Application (SPA)
# This ensures React Router works properly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (set these in Netlify UI)
# VITE_SUPABASE_URL = "your-supabase-url"
# VITE_SUPABASE_ANON_KEY = "your-supabase-anon-key"
